import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')console.log(m.type(),m.text());});
await page.goto(process.env.PLAY_URL||'http://localhost:5173');
await page.waitForFunction(()=>!!window.ironwood,{timeout:30000});
await expect(page.getByRole('heading',{name:'IRONWOOD™'})).toBeVisible();
const snap=()=>page.evaluate(()=>window.ironwood.snapshot());
const point=(x,z)=>page.evaluate(([x,z])=>window.ironwood.project(x,z),[x,z]);
const clickTile=async(x,z)=>{const p=await point(x,z);await page.mouse.click(p.x,p.y);};
await page.keyboard.press('Space');
await expect(page.getByRole('button',{name:'Resume simulation'})).toBeVisible();
const start=await snap();
assert.equal(start.buildings.length,0);
await expect(page.locator('#mission-title')).toHaveText('Start with timber');
await page.getByRole('tab',{name:'Logistics'}).click();
await page.getByRole('button',{name:'Build Storage chest',exact:true}).click();
await clickTile(1,0);
await expect.poll(async()=>(await snap()).buildings.length).toBe(start.buildings.length+1);
const built=await snap();assert.equal(built.inventory.log,start.inventory.log-8);
await clickTile(1,0);assert.equal((await snap()).buildings.length,built.buildings.length);
await page.keyboard.press('Escape');
await clickTile(1,0);await expect(page.locator('#inspector h2')).toHaveText('Storage chest');
await page.getByRole('button',{name:'Close inspector'}).click();
await page.keyboard.press('KeyX');await clickTile(1,0);
await expect.poll(async()=>(await snap()).buildings.length).toBe(start.buildings.length);
assert.equal((await snap()).inventory.log,start.inventory.log);
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Build Conveyor',exact:true}).click();
const p1=await point(0,0),p2=await point(3,0),p3=await point(3,1);
await page.mouse.move(p1.x,p1.y);await page.mouse.down();await page.mouse.move(p2.x,p2.y,{steps:3});await page.mouse.move(p3.x,p3.y,{steps:2});await page.mouse.up();
await expect.poll(async()=>(await snap()).buildings.filter(b=>b.kind==='conveyor'&&b.z===0).length).toBe(4);
assert.equal((await snap()).buildings.find(b=>b.x===3&&b.z===0).dir,1);
await page.keyboard.press('Escape');
await page.keyboard.press('Space');
const beforeWalk=(await snap()).player;
await page.keyboard.down('KeyD');await page.waitForTimeout(750);await page.keyboard.up('KeyD');
const afterWalk=(await snap()).player;assert.ok(Math.hypot(afterWalk.x-beforeWalk.x,afterWalk.z-beforeWalk.z)>.5);
await page.getByRole('button',{name:'Open handcrafting'}).click();
await expect(page.getByRole('heading',{name:'A little handiwork.'})).toBeVisible();
const beforeCraft=(await snap()).inventory;
await page.locator('[data-craft="plank"]').click();assert.equal((await snap()).inventory.plank,beforeCraft.plank+2);assert.equal((await snap()).inventory.log,beforeCraft.log-1);
await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByRole('button',{name:'Open settings'}).click();await page.getByRole('button',{name:'Save workshop',exact:true}).click();
const beforeSave=await snap();await page.reload();await page.waitForFunction(()=>!!window.ironwood);
const restored=await snap();assert.equal(restored.buildings.length,beforeSave.buildings.length);assert.deepEqual(restored.inventory,beforeSave.inventory);assert.deepEqual(restored.player,beforeSave.player);
await page.getByRole('button',{name:'Field guide',exact:true}).click();await expect(page.getByRole('heading',{name:'Small beginnings. Extraordinary possibilities.'})).toBeVisible();await page.getByRole('button',{name:'Close dialog'}).click();
await page.waitForTimeout(5000);
await page.screenshot({path:'.context/ironwood-playtest.png'});
const diagnostics=await page.evaluate(()=>window.ironwood.diagnostics());
console.log('BROWSER CHECKS PASSED: loading, build costs, occupancy, inspect, dismantle refund, continuous belts and corners, movement, crafting, save/reload, guide.');
console.log('DIAGNOSTICS',diagnostics);
assert.deepEqual(errors,[]);
await page.setViewportSize({width:1024,height:768});await page.screenshot({path:'.context/ironwood-1024.png'});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);
await page.setViewportSize({width:1440,height:1000});
await browser.close();
